In [7]:
import numpy as np
import pandas as pd
import statsmodels.api as sm


In [3]:
data = pd.read_excel(r'C:\Users\Moriarty\Desktop\数学\应用统计方法\hw第五周\data1.xls')
data

y  x1  x2   x3
0  160  70  35  1.0
1  260  75  40  2.4
2  210  65  40  2.0
3  265  74  42  3.0
4  240  72  38  1.2
5  220  68  45  1.5
6  275  78  42  4.0
7  160  66  36  2.0
8  275  70  44  3.2
9  250  65  42  3.0

In [10]:
data.corr()

y        x1        x2        x3
y   1.000000  0.555653  0.730620  0.723535
x1  0.555653  1.000000  0.112951  0.398387
x2  0.730620  0.112951  1.000000  0.547474
x3  0.723535  0.398387  0.547474  1.000000

In [32]:
    x = sm.add_constant(data.iloc[:,1:]) #生成自变量
    y = data['y'] #生成因变量
    model = sm.OLS(y, x) #生成模型
    result = model.fit() #模型拟合
    result.summary() #模型描述


D:\py\lib\site-packages\scipy\stats\stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.806
Model:                            OLS   Adj. R-squared:                  0.708
Method:                 Least Squares   F-statistic:                     8.283
Date:                Thu, 24 Mar 2022   Prob (F-statistic):             0.0149
Time:                        22:16:16   Log-Likelihood:                -43.180
No. Observations:                  10   AIC:                             94.36
Df Residuals:                       6   BIC:                             95.57
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -348.2802    176.459     -1.974      0.096    -780.060      83.500
x1             3.7540      1.933      1.942      0.100      -0.977       8.485
x2             7.1007      2.880      2.465      0.049       0.053      14.149
x3            12.4475     10.569      1.178      0.284     -13.415      38.310
==============================================================================
Omnibus:                        0.619   Durbin-Watson:                   1.935
Prob(Omnibus):                  0.734   Jarque-Bera (JB):                0.562
Skew:                           0.216   Prob(JB):                        0.755
Kurtosis:                       1.922   Cond. No.                     1.93e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.93e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [57]:
from math import sqrt
from scipy import stats

sig = sqrt(sum(result.resid**2)/6)

t = stats.t.ppf(1-0.025, 6)
x0 = [1,75,42,3.1]
y0 = result.predict(x0)[0]

c = np.matrix(x0)*np.linalg.inv(np.matrix(x).T*np.matrix(x))*np.matrix(x0).T
c = float(c)
rang = [y0-t*sig*sqrt(c), y0+t*sig*sqrt(c)]
rang

[241.63377262850625, 298.54555613947235]

In [22]:
print(np.linalg.inv(np.matrix(x).T*np.matrix(x)))

[[ 5.66635567e+01 -4.99180263e-01 -6.36339069e-01  1.81841811e+00]
 [-4.99180263e-01  6.80174603e-03  1.38828204e-03 -1.50511059e-02]
 [-6.36339069e-01  1.38828204e-03  1.50968010e-02 -3.05441717e-02]
 [ 1.81841811e+00 -1.50511059e-02 -3.05441717e-02  2.03287196e-01]]


In [28]:
def looper(limit):
    cols = ['x1', 'x2', 'x3']
    for i in range(len(cols)):
        data1 = data[cols]
        x = sm.add_constant(data1) #生成自变量
        y = data['y'] #生成因变量
        model = sm.OLS(y, x) #生成模型
        result = model.fit() #模型拟合
        pvalues = result.pvalues #得到结果中所有P值
        pvalues.drop('const',inplace=True) #把const取得
        pmax = max(pvalues) #选出最大的P值
        if pmax>limit:
            ind = pvalues.idxmax() #找出最大P值的index
            cols.remove(ind) #把这个index从cols中删除
        else:
            return result
    
result = looper(0.1)
result.summary()

D:\py\lib\site-packages\scipy\stats\stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.761
Model:                            OLS   Adj. R-squared:                  0.692
Method:                 Least Squares   F-statistic:                     11.12
Date:                Thu, 24 Mar 2022   Prob (F-statistic):            0.00672
Time:                        21:14:14   Log-Likelihood:                -44.220
No. Observations:                  10   AIC:                             94.44
Df Residuals:                       7   BIC:                             95.35
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -459.6237    153.058     -3.003      0.020    -821.547     -97.700
x1             4.6756      1.816      2.575      0.037       0.381       8.970
x2             8.9710      2.468      3.634      0.008       3.134      14.808
==============================================================================
Omnibus:                        1.265   Durbin-Watson:                   1.895
Prob(Omnibus):                  0.531   Jarque-Bera (JB):                0.631
Skew:                          -0.587   Prob(JB):                        0.730
Kurtosis:                       2.630   Cond. No.                     1.63e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.63e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [30]:
def mean_norm(df_input):
    return df_input.apply(lambda x: (x-x.mean())/ x.std(), axis=0)

data0 = mean_norm(data)
data0

y        x1        x2        x3
0 -1.647443 -0.067439 -1.649972 -1.376599
1  0.656673  1.056543 -0.122220  0.072453
2 -0.495385 -1.191421 -0.122220 -0.341562
3  0.771879  0.831747  0.488881  0.693475
4  0.195850  0.382154 -0.733321 -1.169592
5 -0.264973 -0.517032  1.405531 -0.859080
6  1.002291  1.730932  0.488881  1.728511
7 -1.647443 -0.966624 -1.344421 -0.341562
8  1.002291 -0.067439  1.099981  0.900482
9  0.426261 -1.191421  0.488881  0.693475

In [31]:
x = sm.add_constant(data0.iloc[:,1:]) #生成自变量
y = data0['y'] #生成因变量
model = sm.OLS(y, x) #生成模型
result = model.fit() #模型拟合
result.summary() #模型描述

D:\py\lib\site-packages\scipy\stats\stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.806
Model:                            OLS   Adj. R-squared:                  0.708
Method:                 Least Squares   F-statistic:                     8.283
Date:                Thu, 24 Mar 2022   Prob (F-statistic):             0.0149
Time:                        21:48:40   Log-Likelihood:                -5.4758
No. Observations:                  10   AIC:                             18.95
Df Residuals:                       6   BIC:                             20.16
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -8.327e-17      0.171  -4.88e-16      1.000      -0.418       0.418
x1             0.3848      0.198      1.942      0.100      -0.100       0.870
x2             0.5355      0.217      2.465      0.049       0.004       1.067
x3             0.2771      0.235      1.178      0.284      -0.299       0.853
==============================================================================
Omnibus:                        0.619   Durbin-Watson:                   1.935
Prob(Omnibus):                  0.734   Jarque-Bera (JB):                0.562
Skew:                           0.216   Prob(JB):                        0.755
Kurtosis:                       1.922   Cond. No.                         2.15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""